local Card = require("src.ui.card")

local APP_WIDTH = 1920
local APP_HEIGHT = 1080

local CARD_BODY_ASPECT_WIDTH = 300
local CARD_BODY_ASPECT_HEIGHT = 280
local CARD_WIDTH = 150
local CARD_BODY_HEIGHT = math.floor((CARD_WIDTH * CARD_BODY_ASPECT_HEIGHT / CARD_BODY_ASPECT_WIDTH) + 0.5)
local CARD_HEADER_HEIGHT = Card.HEADER_HEIGHT or 34
local CARD_HEIGHT = CARD_HEADER_HEIGHT + CARD_BODY_HEIGHT

return {
    APP_WIDTH = APP_WIDTH,
    APP_HEIGHT = APP_HEIGHT,
    WORLD_WIDTH = APP_WIDTH * 2,
    WORLD_HEIGHT = APP_HEIGHT * 2,

    CARD_WIDTH = CARD_WIDTH,
    CARD_HEIGHT = CARD_HEIGHT,
    CARD_HEADER_HEIGHT = CARD_HEADER_HEIGHT,

    BOOSTER_PACK_WIDTH_SCALE = 1.265,
    BOOSTER_PACK_ASPECT = 1280 / 1024,

    STACK_OFFSET_Y = CARD_HEADER_HEIGHT - 14,
    STACK_SNAP_DISTANCE = 88,
    CLICK_ATTACH_THRESHOLD = 6,

    WORK_BAR_HEIGHT = 24,
    WORK_BAR_FILL_MARGIN_X = 6,
    WORK_BAR_FILL_MARGIN_Y = 6,
    WORK_BAR_FILL_RADIUS = 8,
    WORK_BAR_FILL_RIGHT_TRIM = 4,

    OFFICE_BACKGROUND_PATH = "assets/handdrawn/officebg.png",

    SPRINT_DURATION_SECONDS = 60,
}
